# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "0":{
      x: 91,
      y: 37,
      yaw: 90},
    "1":{
      x: 91,
      y: 37,
      yaw: 90},
    "2":{
      x: 93,
      y: 37,
      yaw: 90},
    "3":{
      x: 95,
      y: 37,
      yaw: 90},
    "4":{
      x: 97,
      y: 37,
      yaw: 90},
  },
  "2":{
    "5":{
      x: 31,
      y: 413,
      yaw: 90},
    "6":{
      x: 33,
      y: 413,
      yaw: 90},
    "7":{
      x: 35,
      y: 413,
      yaw: 90},
    "8":{
      x: 37,
      y: 413,
      yaw: 90},
    "9":{
      x: 39,
      y: 413,
      yaw: 90},
  },
}
