# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "0":{
      x: 185,
      y: 76,
      yaw: 90},
    "1":{
      x: 185,
      y: 76,
      yaw: 90},
    "2":{
      x: 187,
      y: 76,
      yaw: 90},
    "3":{
      x: 189,
      y: 76,
      yaw: 90},
    "4":{
      x: 191,
      y: 76,
      yaw: 90},
  },
  "2":{
    "5":{
      x: 180,
      y: 475,
      yaw: 90},
    "6":{
      x: 182,
      y: 475,
      yaw: 90},
    "7":{
      x: 184,
      y: 475,
      yaw: 90},
    "8":{
      x: 186,
      y: 475,
      yaw: 90},
    "9":{
      x: 188,
      y: 475,
      yaw: 90},
  },
}
