# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "0":{
      x: 119,
      y: 49,
      yaw: 90},
    "1":{
      x: 119,
      y: 49,
      yaw: 90},
    "2":{
      x: 121,
      y: 49,
      yaw: 90},
    "3":{
      x: 123,
      y: 49,
      yaw: 90},
    "4":{
      x: 125,
      y: 49,
      yaw: 90},
  },
  "2":{
    "5":{
      x: 191,
      y: 480,
      yaw: 90},
    "6":{
      x: 193,
      y: 480,
      yaw: 90},
    "7":{
      x: 195,
      y: 480,
      yaw: 90},
    "8":{
      x: 197,
      y: 480,
      yaw: 90},
    "9":{
      x: 199,
      y: 480,
      yaw: 90},
  },
}
